name: Build Azahar (Windows ARM64/AArch64)

on:
  push:
    branches:
      - master

jobs:
  build-winarm64:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-11-arm
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANGARM64
          update: true
          pacboy: >-
            cmake:p
            ninja:p
            qt6:p
            spirv-tools:p
            toolchain:p
      - name: Build
        run: |
          cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_QT_TRANSLATION=ON -DUSE_DISCORD_PRESENCE=ON
          cmake --build build
          cmake --build build -- bundle
      - name: Copy files
        shell: bash
        run: |
          cp license.txt build/bundle/license.txt
          install -Dv /dev/null build/bundle/user/user.txt
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: azahar-git-windows-arm64-msys2-${{github.sha}}
          path: build/bundle
          if-no-files-found: error
